// <auto-generated />
using System;
using ElderCareApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ElderCareApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260129041850_AddStaffAndHealth")]
    partial class AddStaffAndHealth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ElderCareApp.Models.CareHome", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ManagerEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ManagerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CareHomes");
                });

            modelBuilder.Entity("ElderCareApp.Models.Elder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CareHomeId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.ToTable("Elders");
                });

            modelBuilder.Entity("ElderCareApp.Models.ElderHealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateRecorded")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ElderId")
                        .HasColumnType("int");

                    b.Property<int>("HeartRate")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElderId");

                    b.HasIndex("StaffId");

                    b.ToTable("ElderHealthRecords");
                });

            modelBuilder.Entity("ElderCareApp.Models.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CareHomeId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CareHomeId");

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("ElderCareApp.Models.Elder", b =>
                {
                    b.HasOne("ElderCareApp.Models.CareHome", "CareHome")
                        .WithMany("Elders")
                        .HasForeignKey("CareHomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHome");
                });

            modelBuilder.Entity("ElderCareApp.Models.ElderHealthRecord", b =>
                {
                    b.HasOne("ElderCareApp.Models.Elder", "Elder")
                        .WithMany()
                        .HasForeignKey("ElderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElderCareApp.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Elder");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("ElderCareApp.Models.Staff", b =>
                {
                    b.HasOne("ElderCareApp.Models.CareHome", "CareHome")
                        .WithMany()
                        .HasForeignKey("CareHomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CareHome");
                });

            modelBuilder.Entity("ElderCareApp.Models.CareHome", b =>
                {
                    b.Navigation("Elders");
                });
#pragma warning restore 612, 618
        }
    }
}
